version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    # Reads environment variables from the .env file
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_SERVER_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      # Bind host path to container path
      - "${MINIO_DATA_PATH}:/data"
    command: server /data --console-address ":9001"
